a few of my chapters
jajunk/LightHouseLinuxMasterMDFiles pull request #7
Opened 2024-07-22 22:00 UTC by Ganome

See commit history for more details

2024-07-26 23:30 UTC, jajunk requested changes
@Ganome

I have updated the pull request to target the `dev` branch instead of `main`. Please ensure to direct future pull requests to the `dev` branch as well.

Additionally, I noticed that the markdown guide is not being followed. I have linked the guide in a comment on the first file for your reference.

Could you please confirm if you will be handling both the content generation and the styling, or if we should assign the styling to someone else?

2024-07-26 23:30 UTC, jajunk commented on Linux Permissions and Ownership/The sudo Command.md
Doesn't follow the standard Markdown syntax

2024-07-26 23:30 UTC, jajunk commented on Linux Permissions and Ownership/The sudo Command.md
I editied this file to reflect the standard Markdown format. Please review the below link for assistance. 

[MarkDownStyleGuide](https://github.com/jajunk/LightHouseLinuxMasterMDFiles/blob/dev/LightHouseMarkDownStyleGuide.md)

2024-07-28 20:28 UTC, Ganome commented
I believe these changes now meet the styling guide.

2024-07-28 21:07 UTC, jajunk commented
I will look this over and merge it in the morning. Thank you for making these changes.

2024-07-31 07:27 UTC, merged